function air = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  AIR = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  AIR = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  AIR = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  air = importfile("D:\TurboJet Code\Matlab\air.xlsx", "Sheet1", [5, 126]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Nov-2022 21:59:33

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [5, 126];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "whens0", "VarName6"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Import the data
air = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    air = [air; tb]; %#ok<AGROW>
end

%% Convert to output type
air = table2array(air);
end