function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, xdata1, ydata1, zdata1)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, xdata1, ydata1, zdata1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  Y6:  vector of y data
%  X7:  vector of x data
%  Y7:  vector of y data
%  X8:  vector of x data
%  Y8:  vector of y data
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 05-Apr-2023 23:03:12

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Color',[0 0.447 0.741]);

% Create text
text('Parent',axes1,'String','5000','Position',[0 2.17343164402251 0]);

% Create plot
plot(X2,Y2,'Color',[0 0.447 0.741]);

% Create text
text('Parent',axes1,'String','6000','Position',[0 3.13525733325446 0]);

% Create plot
plot(X3,Y3,'Color',[0 0.447 0.741]);

% Create text
text('Parent',axes1,'String','7000','Position',[0 5.13093098956431 0]);

% Create plot
plot(X4,Y4,'Color',[0 0.447 0.741]);

% Create text
text('Parent',axes1,'String','8000','Position',[0 9.09421828835013 0]);

% Create plot
plot(X5,Y5,'Color',[0 0.447 0.741]);

% Create text
text('Parent',axes1,'String','9000','Position',[0 16.8738732831209 0]);

% Create plot
plot(X6,Y6,'Color',[0 0.447 0.741]);

% Create text
text('Parent',axes1,'String','10000','Position',[0 31.7546607013391 0]);

% Create plot
plot(X7,Y7,'Color',[0 0.447 0.741]);

% Create text
text('Parent',axes1,'String','11000','Position',[0 59.1575078773722 0]);

% Create plot
plot(X8,Y8,'DisplayName','Analytical form spine','Color',[0 0 0]);

% Create contour
[c1,h1] = contour(xdata1,ydata1,zdata1,...
    'DisplayName','Isentropic Efficiency',...
    'LineColor',[0.929 0.694 0.125],...
    'LevelList',[0.6 0.65 0.7 0.75 0.8 0.85 0.9],...
    'LabelSpacing',350);
clabel(c1,h1);

% Create ylabel
ylabel('Pressure ratio');

% Create xlabel
xlabel('Corrected mass flow rate');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 39]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1 39]);
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest');

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

end
